service: yaipes

frameworkVersion: ">=1.28.0 <2.0.0"

provider:
  name: aws
  runtime: go1.x
  stage: prod
  region: ca-central-1

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  ipecho:
    handler: bin/ipecho
    description: Returns the IP Address of the client
    memory: 128
    timeout: 5
    events:
      - http: 
          method: GET 
          path: /

